### ISSUE TITLE
NickName

### ISSUE THREAD

**Issue by peyman1959** [includeamin/Mads_Documentation#16]
set:
/users/info/update
get:
/users/session/start
/match/init
/match/users/get

**Comment by includeamin** [comment]
okaye emruz miznm migm bet

**Comment by includeamin** [comment]
/users/info/update
Kilide NickName ezafe shode be addesh 
 baghie jaha ham mide
ye init game kon  bbin droste y  na?

**Comment by includeamin** [comment]
PurchasedShopItemList ham ezafe shode bud be user ha
shop item bekhar bbin drost kar mikone ya na
