### ISSUE TITLE
ShopItem not found

### ISSUE THREAD

**Issue by peyman1959** [includeamin/Mads_Documentation#17]
Url
https://resource.themaddays.com/shop/buy/5d91b4b5a7a24c796ac8a30b
Responce
{"State": false, "Description": "item not found"}
ShopItem id 5d91b4b5a7a24c796ac8a30b
Gameitem id
5d91bb0ba7a24c70e5c8a310

**Comment by includeamin** [comment]
id shop item e k midi mojud nist tu database
